In [7]:

import numpy as np
import pandas as pd

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)


# =========================================================
# 1. LOAD DATASET
# =========================================================

df = pd.read_csv("BankNote_Authentication.csv")

print("Original Dataset:")
display(df.head())

print("\nDataset Shape:", df.shape)


# =========================================================
# 2. DATA CLEANING
# =========================================================

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

# Remove missing values
df = df.dropna()

print("\nDuplicate Rows:", df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

print("\nCleaned Dataset:")
display(df.head())

print("\nCleaned Dataset Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)


# =========================================================
# 3. FEATURES AND LABELS
# =========================================================

X = df[
    [
        "variance",
        "skewness",
        "curtosis",
        "entropy"
    ]
].values

y = df["class"].values

print("\nFeatures Shape:", X.shape)
print("Labels Shape:", y.shape)


# =========================================================
# 4. STEP FUNCTION
# =========================================================

def step_function(x):
    return 1 if x >= 0 else 0


# =========================================================
# 5. PERCEPTRON CLASS
# =========================================================

class Perceptron:

    def __init__(self, input_size):
        self.weights = np.zeros(input_size)
        self.bias = 0
        self.learning_rate = 0.15

    def predict(self, x):
        weighted_sum = np.dot(self.weights, x) + self.bias
        return step_function(weighted_sum)

    def train(self, X, y, epochs):

        for epoch in range(epochs):

            for xi, yi in zip(X, y):

                y_pred = self.predict(xi)

                error = yi - y_pred

                self.weights += (
                    self.learning_rate * error * xi
                )

                self.bias += (
                    self.learning_rate * error
                )


# =========================================================
# 6. CREATE PERCEPTRON
# =========================================================

perceptron = Perceptron(input_size=4)

print("\nInitial Weights:", perceptron.weights)
print("Initial Bias:", perceptron.bias)


# =========================================================
# 7. TRAIN MODEL
# =========================================================

perceptron.train(X, y, epochs=300)

print("\nModel Training Completed")

print("Final Weights:", perceptron.weights)
print("Final Bias:", perceptron.bias)


# =========================================================
# 8. FIRST 10 PREDICTIONS
# =========================================================

print("\nFirst 10 Predictions:")

for xi in X[:10]:

    prediction = perceptron.predict(xi)

    print(
        f"Input: {xi}, "
        f"Prediction: {prediction}"
    )


# =========================================================
# 9. PREDICT COMPLETE DATASET
# =========================================================

y_pred = np.array([
    perceptron.predict(xi)
    for xi in X
])


# =========================================================
# 10. CONFUSION MATRIX
# =========================================================

cm = confusion_matrix(y, y_pred)

print("\nConfusion Matrix:")
print(cm)


# =========================================================
# 11. EVALUATION METRICS
# =========================================================

accuracy = accuracy_score(y, y_pred)

precision = precision_score(y, y_pred)

recall = recall_score(y, y_pred)

f1 = f1_score(y, y_pred)


print("\nEvaluation Metrics")
print("-------------------")

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)


# =========================================================
# 12. CLASSIFICATION REPORT
# =========================================================

print("\nClassification Report:")
print(classification_report(y, y_pred))

Original Dataset:

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

Dataset Shape: (16, 5)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   variance  16 non-null     float64
 1   skewness  16 non-null     float64
 2   curtosis  16 non-null     float64
 3   entropy   16 non-null     float64
 4   class     16 non-null     int64
dtypes: float64(4), int64(1)
memory usage: 772.0 bytes

Missing Values:
variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

Duplicate Rows: 0

Cleaned Dataset:

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

Cleaned Dataset Shape: (16, 5)

Data Types:
variance    float64
skewness    float64
curtosis    float64
entropy     float64
class         int64
dtype: object

Features Shape: (16, 4)
Labels Shape: (16,)

Initial Weights: [0. 0. 0. 0.]
Initial Bias: 0

Model Training Completed
Final Weights: [-1.4043315  0.0904695  0.071985  -0.1565955]
Final Bias: -0.14999999999999994

First 10 Predictions:
Input: [ 3.6216   8.6661  -2.8073  -0.44699], Prediction: 0
Input: [ 4.5459  8.1674 -2.4586 -1.4621], Prediction: 0
Input: [ 3.866   -2.6383   1.9242   0.10645], Prediction: 0
Input: [ 3.4566  9.5228 -4.0112 -3.5944], Prediction: 0
Input: [ 0.32924 -4.4552   4.5718  -0.9888 ], Prediction: 0
Input: [ 4.3684  9.6718 -3.9606 -3.1625], Prediction: 0
Input: [3.5912  3.0129  0.72888 0.56421], Prediction: 0
Input: [ 2.0922  -6.81     8.4636  -0.60216], Prediction: 0
Input: [-0.24877 -0.17797  4.9068   0.15429], Prediction: 1
Input: [-1.2966  2.3537 -0.7382 -2.5276], Prediction: 1

Confusion Matrix:
[[8 0]
 [0 8]]

Evaluation Metrics
-------------------
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         8

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16